name: Renovate
on:
# TODO replace push and workflow_dispatch by the schedule
  push:
    branches: [ "renovate-setup" ]
  workflow_dispatch:
#  schedule:
#    # Daily, at midnight.
#    - cron: '0 0 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}